name: hgs_sound
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hgs_framework:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: framework
  hgs_device_info:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: device_info

  ## 提示音播放 android ios macos web
  soundpool: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

