name: hg_framework
description: hg_framework
version: 1.2.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  theme:
    path: packages/theme

  # uuid
  uuid: ^3.0.7

  # 框架类的库
  ## 依赖、状态管理、路由框架
  get: ^4.6.5
  ## 异常处理 暂时不需要，是上报服务器的异常
  # sentry_flutter: ^6.2.2

  # 数据库支持
  path: ^1.8.2
  sembast: ^3.3.1
  sembast_web: ^2.0.1+1

  # 设备功能的库
  ## 本地存储
  shared_preferences: ^2.0.15
  ## 路径 except web
  path_provider: ^2.0.11
  ## 打开链接
  url_launcher: ^6.1.7
  ## 权限请求 android ios windows
  permission_handler: ^10.2.0
  ## todo 提示音播放 android ios macos web
  soundpool: ^2.3.0
  ## 设备信息 all
  device_info_plus: ^4.1.3
  ## 网络链接检查 all
  connectivity_plus: ^2.3.9



  # 移动端专用库
  ## 本地通知 android ios macos linux
  flutter_local_notifications: ^9.9.1
  ## 本地时区 本地通知用 android ios web
  flutter_native_timezone: ^2.0.0
  timezone: ^0.8.0

  # 桌面端专用库
  ## 窗口设置
  window_manager: ^0.2.7
  ## 本地通知
  local_notifier: ^0.1.5

  # web端专用库
  ## 解析浏览器userAgent
  user_agent_analyzer: ^4.0.0
  ## 因为手势后退的原因，打不开drawer所以加这个手势监听
  simple_gesture_detector: ^0.2.0

  # 其它功能的库
  ## 日志
  logger: ^1.1.0
  ## 日期格式化
  date_format: ^2.0.6
  dart_date: ^1.1.1

  # 布局的库
  ## 拖拽排序
  reorderables: ^0.5.1
  ## 组件扩展
  styled_widget: ^0.4.0+3

  # 图标、动画、字体的库
  ## 加载动画
  flutter_spinkit: ^5.1.0
  ## 动画
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
