
/// @file AddTextTwo 文字
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper addtexttwo = iconWrapper('add-text-two', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<circle cx="24" cy="24" r="20" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M32 16H16" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M24 34V16" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
