
/// @file ApplicationTwo 应用
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper applicationtwo = iconWrapper('application-two', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<circle cx="34.5" cy="13.5" r="6.5" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<circle cx="34.5" cy="34.5" r="6.5" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<circle cx="13.5" cy="13.5" r="6.5" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<circle cx="13.5" cy="34.5" r="6.5" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
   '</svg>'
),);
