
/// @file CheckCorrect 对勾
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper checkcorrect = iconWrapper('check-correct', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<g clip-path="url(#${props.id}353e4f38)">'
           '<path d="M42 20V39C42 40.6569 40.6569 42 39 42H9C7.34315 42 6 40.6569 6 39V9C6 7.34315 7.34315 6 9 6H30" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M16 20L26 28L41 7" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '</g>'
       '<defs>'
           '<clipPath id="${props.id}353e4f38">'
               '<rect width="48" height="48" fill="${props.colors[2]}"/>'
           '</clipPath>'
       '</defs>'
   '</svg>'
),);
