
/// @file Dropbox 管理箱
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper dropbox = iconWrapper('dropbox', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<g clip-path="url(#${props.id}78df3014)">'
           '<path d="M24 10L12 18L24 26L36 18L24 10Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M24 10L36 18L41 11L30 4L24 10Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M24 10L12 18L7 11L18 4L24 10Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M43 22L36 18L24 26L31 31L43 22Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M5 22L12 18L24 26L17 31L5 22Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M36 28V37L24 44L12 37V28" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '</g>'
       '<defs>'
           '<clipPath id="${props.id}78df3014">'
               '<rect width="48" height="48" fill="${props.colors[2]}"/>'
           '</clipPath>'
       '</defs>'
   '</svg>'
),);
