
/// @file Dubai 迪拜大厦
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper dubai = iconWrapper('dubai', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M14 4L14 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
       '<path d="M14.5 6C14.5 6 28 13 32 22C36 31 33 44 33 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M4 44H44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M10 15H32" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
       '<path d="M14 22H22" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
       '<path d="M14 29H26" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
       '<path d="M14 36H27" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
   '</svg>'
),);
