
/// @file Hospital 医院
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper hospital = iconWrapper('hospital', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M33 5H5V43H33V5Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M33 21H43V43H33" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M13 21H25" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
       '<path d="M19 15V27" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}"/>'
   '</svg>'
),);
