
/// @file KeyOne 钥匙1
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper keyone = iconWrapper('key-one', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<g clip-path="url(#${props.id}7770af78)">'
           '<circle cx="15" cy="33" r="8" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
           '<path d="M29 16L35.5 22" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M20 26L37 7" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M35 11L42 17.5" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '</g>'
       '<defs>'
           '<clipPath id="${props.id}7770af78">'
               '<rect width="48" height="48" fill="${props.colors[2]}"/>'
           '</clipPath>'
       '</defs>'
   '</svg>'
),);
