
/// @file KnifeFork 刀子叉子
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper knifefork = iconWrapper('knife-fork', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M14 4V44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M8 5V15C8 20 14 20 14 20C14 20 20 20 20 15V5" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M30 12C30 4 38 4 38 4V21H30V12Z" fill="${props.colors[1]}"/>'
       '<path d="M38 21H30V12C30 4 38 4 38 4V21ZM38 21V44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
