
/// @file Lightning 闪电
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper lightning = iconWrapper('lightning', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M19 4H37L26 18H41L17 44L22 25H8L19 4Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
