
/// @file OvalOne 椭圆形
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper ovalone = iconWrapper('oval-one', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<ellipse cx="24" cy="24" rx="14" ry="20" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
   '</svg>'
),);
