
/// @file RouterOne 路由器
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper routerone = iconWrapper('router-one', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M10 24L4 38H44L38 24H10Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path fill-rule="evenodd" clip-rule="evenodd" d="M10 4V24V4Z" fill="${props.colors[1]}"/>'
       '<path d="M10 4V24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path fill-rule="evenodd" clip-rule="evenodd" d="M38 4V24V4Z" fill="${props.colors[1]}"/>'
       '<path d="M38 4V24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path fill-rule="evenodd" clip-rule="evenodd" d="M24 4V24V4Z" fill="${props.colors[1]}"/>'
       '<path d="M24 4V24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M4 38V44H44V38" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
