
/// @file ViewGridCard 卡片查看模式
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper viewgridcard = iconWrapper('view-grid-card', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<rect x="6" y="6" width="36" height="36" rx="3" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="13" y="13" width="8" height="8" fill="${props.colors[3]}" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="27" y="13" width="8" height="8" fill="${props.colors[3]}" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="13" y="27" width="8" height="8" fill="${props.colors[3]}" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="27" y="27" width="8" height="8" fill="${props.colors[3]}" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
