name: hgs_toast
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hgs_framework:
    path: ../framework
  hgs_device_info:
    path: ../device_info
  hgs_components:
    path: ../components
  hgs_route:
    path: ../route

  flutter_spinkit: ^5.1.0
  uuid: ^3.0.7
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

