name: hgs_iconpark_svg
description: iconpark以svg形式呈现
version: 0.0.1
publish_to: none


environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hgs_icon:
    path: ../icon

  ## svg图标
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: