name: hgs_iconpark_font
description: iconpark图标以font图标呈现。
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hgs_icon:
    path: ../icon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: IconPark
      fonts:
        - asset: fonts/iconpark.ttf

