name: hgs_components
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hgs_framework:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: framework
  hgs_route:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: route
  hgs_device_info:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: device_info
  ## 打开链接
  url_launcher: ^6.1.7
  ## 因为手势后退的原因，打不开drawer所以加这个手势监听
  simple_gesture_detector: ^0.2.0

  # 布局的库
  ## 拖拽排序
  reorderables: ^0.5.1
  ## 组件扩展
  styled_widget: ^0.4.1

  # 图标、动画、字体的库
  ## 加载动画
  flutter_spinkit: ^5.1.0
  ## 动画
  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

