
/// @file Bluetooth 蓝牙
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper bluetooth = iconWrapper('bluetooth', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M12 13L34 34L23 44V4L34 14L12 35" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
