
/// @file Classroom 课堂
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper classroom = iconWrapper('classroom', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<circle cx="24" cy="13" r="9" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M5 44C5 35.5625 11.175 27.6875 16.4 26C16.4 26 21.15 31.0625 24 34.4375L31.6 26C35.875 26.5625 43 35.5625 43 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M2 44L46 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
