
/// @file DiskTwo U盘2
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper disktwo = iconWrapper('disk-two', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<rect x="4" y="13" width="32" height="22" rx="2" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M4 13H14V35H4V13Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M36 19H44V29H36" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<circle cx="30" cy="21" r="2" fill="${props.colors[0]}"/>'
       '<circle cx="30" cy="27" r="2" fill="${props.colors[0]}"/>'
   '</svg>'
),);
