
/// @file Doughnut 甜甜圈
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper doughnut = iconWrapper('doughnut', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<circle cx="24" cy="24" r="19" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<circle cx="24" cy="24" r="7" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M6 28C6 28 9.38888 25.0417 12 27C16 30 18 28 18 28" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M29 29C29.6667 28 33 24.7143 36 26C40 27.7143 43 26 43 25" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
