
/// @file FileSearchOne 文件搜索1
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper filesearchone = iconWrapper('file-search-one', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M40 23V14L31 4H10C8.89543 4 8 4.89543 8 6V42C8 43.1046 8.89543 44 10 44H22" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<circle cx="31" cy="34" r="6" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M36 38L41 42" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M30 4V14H40" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
