
/// @file FutureBuildTwo 未来魔都
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper futurebuildtwo = iconWrapper('future-build-two', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M4 44H44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<ellipse cx="24.5" cy="7" rx="13.5" ry="3" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M16 9C16 9 20.1593 17.8828 21 24C22.0687 31.7763 20 44 20 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M32.2266 9C32.2266 9 28.0673 17.8828 27.2266 24C26.1578 31.7763 28.0006 44 28.0006 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
   '</svg>'
),);
