
/// @file GameConsole 游戏机
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper gameconsole = iconWrapper('game-console', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<rect x="10" y="4" width="28" height="40" rx="2" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M16 34H24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M20 30V38" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="16" y="10" width="16" height="9" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<circle cx="31" cy="30" r="2" fill="${props.colors[0]}"/>'
       '<circle cx="31" cy="38" r="2" fill="${props.colors[0]}"/>'
   '</svg>'
),);
