
/// @file Gopro 运动相机
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper gopro = iconWrapper('gopro', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<rect x="5" y="7" width="13" height="34" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="24" y="13" width="19" height="22" rx="3" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<circle cx="33.5" cy="24.5" r="3.5" fill="${props.colors[3]}" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M18 24H24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="9" y="15" width="5" height="5" rx="2.5" fill="${props.colors[0]}"/>'
   '</svg>'
),);
