
/// @file GreenHouse 温室房
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper greenhouse = iconWrapper('green-house', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M42 20V44H24H6V20L24 4L42 20Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M6 24L42 24" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M13 14L13 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M35 14L35 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="20" y="32" width="8" height="12" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
