
/// @file KeyTwo 钥匙2
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper keytwo = iconWrapper('key-two', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<g clip-path="url(#${props.id}d91d71d5)">'
           '<circle cx="15" cy="33" r="8" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
           '<path d="M29 16L36 22" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
           '<path d="M20 26L36 8L43 14" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '</g>'
       '<defs>'
           '<clipPath id="${props.id}d91d71d5">'
               '<rect width="48" height="48" fill="${props.colors[2]}"/>'
           '</clipPath>'
       '</defs>'
   '</svg>'
),);
