
/// @file PaintedScreen 绘制屏
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper paintedscreen = iconWrapper('painted-screen', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<rect x="5" y="10" width="38" height="28" rx="3" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}"/>'
       '<path d="M13 24L13 17" stroke="${props.colors[2]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<rect x="15" y="29" width="4" height="4" rx="2" transform="rotate(90 15 29)" fill="${props.colors[2]}"/>'
   '</svg>'
),);
