
/// @file Rowing 划船
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper rowing = iconWrapper('rowing', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M30.0195 16C32.781 16 35.0195 13.7614 35.0195 11C35.0195 8.23858 32.781 6 30.0195 6C27.2581 6 25.0195 8.23858 25.0195 11C25.0195 13.7614 27.2581 16 30.0195 16Z" fill="${props.colors[1]}" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-miterlimit="2"/>'
       '<path d="M42 31L35 44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-miterlimit="2" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M32.01 40L26 29L9 40L21 20L44 25" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-miterlimit="2" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M4 40H44" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-miterlimit="2" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
