
/// @file SplitBranch 分离
/// @author Auto Generated by IconPark
 


import '../runtime.dart';

IIconWrapper splitbranch = iconWrapper('split-branch', (ISvgIconProps props) => (
    '<?xml version="1.0" encoding="UTF-8"?>'
   '<svg width="${props.size}" height="${props.size}" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">'
       '<path d="M44 44V4H24V17L33 26V44H44Z" fill="${props.colors[1]}"/>'
       '<path d="M4 4V44H25V30L16 21V4H4Z" fill="${props.colors[1]}"/>'
       '<path d="M44 44V4H24V17L33 26V44H44Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
       '<path d="M4 4V44H25V30L16 21V4H4Z" stroke="${props.colors[0]}" stroke-width="${props.strokeWidth.toString()}" stroke-linecap="${props.strokeLinecap.value}" stroke-linejoin="${props.strokeLinejoin.value}"/>'
   '</svg>'
),);
