name: hgs_starter
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hgs_framework:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: framework
  hgs_device_info:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: device_info
  hgs_prefs:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: prefs
  hgs_toast:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: toast
  hgs_notification:
    git:
      url: https://github.com/humanghosts/flutter_packages.git
      path: notification

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

