name: notification
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  hgs_framework:
    path: ../framework
  hgs_device_info:
    path: ../device_info
  hgs_database_api:
    path: ../database/database_api
  hgs_toast:
    path: ../toast
  hgs_work:
    path: ../work

  ## 权限请求 android ios windows
  permission_handler: ^10.2.0
  ## 本地通知 android ios macos linux
  flutter_local_notifications: ^9.9.1
  ## 本地时区 本地通知用 android ios web
  flutter_native_timezone: ^2.0.0
  timezone: ^0.8.0
  ## 本地通知 windows mac linux
  local_notifier: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
