name: theme
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hg_framework:
    path: ../framework
  entity:
    path: ../entity

  # TODO 剥离这个依赖
  database_sembast:
    path: ../database/database_sembast

  get: ^4.6.5

  ## 主题
  flex_color_scheme: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

