name: icon_value
description: IconValue 继承 CustomValue用于数据库存储图标
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hg_framework:
    path: ../../../../hg_framework
  icon:
    path: ../icon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
